apiVersion: batch/v1
kind: Job
metadata:
        name: iiitaayushijob25
spec:
  template:
    spec:
      containers:
      - name: iiitaayushijob
        image: nvcr.io/nvidia/tensorflow:19.08-py3_mumax3
        command: ["python"]
        args: ["/workspace/data/src/prepare_dataset.py", "/workspace/data/classification/celeb-df", "--raw", "--color", "tfrecords"]
        env:
        - name: HOME
          value: /home/iiitaayushi
        - name: NVIDIA_VISIBLE_DEVICES 
          value: none
        volumeMounts:
        - name: data
          mountPath: /workspace/data
        - name: nfs
          mountPath: /workspace/storage
        - name: home
          mountPath: /home
        - name: shadow
          mountPath: "/etc/shadow" 
          readOnly: true
        - name: password
          mountPath: "/etc/passwd"
          readOnly: true
        - name: group
          mountPath: "/etc/group"
          readOnly: true
      volumes:
      - name: data
        hostPath:
          path: /raid/iiitaayushi
          type: Directory
      - name: nfs
        hostPath:
          path: /DATA1/iiitaayushi
          type: Directory
      - name: home
        hostPath:
          path: /home/iiitaayushi
          type: Directory
      - name: group
        hostPath:
          path: "/etc/group"
      - name: shadow
        hostPath:
          path: "/etc/shadow"
      - name: password
        hostPath:
          path: "/etc/passwd"
      restartPolicy: Never
  backoffLimit: 1
