apiVersion: batch/v1
kind: Job
metadata:
  name: iiitaayushijobtrain
spec:
  template:
    spec:
      containers:
      - name: iiitaayushijob
        image: nvcr.io/nvidia/tensorflow:19.08-py3_mumax3
        command: ["python"]
        args: ["/workspace/data/src/classifier.py", "train", "xception", "/workspace/data/classification/c23/tfrecords/all_color_raw_train_tf/data.tfrecords", "/workspace/data/classification/c23/tfrecords/all_color_raw_val_tf/data.tfrecords", "/workspace/data/trained_models/", "/workspace/data/checkpoint/ckpt.h5", "-b=32", "--classes=2", "--epochs=100","--image_size=299"]
        env:
        - name: HOME
          value: /home/iiitaayushi
        resources:
          limits:
           nvidia.com/gpu: 2
        volumeMounts:
        - name: data
          mountPath: /workspace/data
        - name: nfs
          mountPath: /workspace/storage
        - name: home
          mountPath: /home
        - name: shadow
          mountPath: "/etc/shadow" 
          readOnly: true
        - name: password
          mountPath: "/etc/passwd"
          readOnly: true
        - name: group
          mountPath: "/etc/group"
          readOnly: true
      volumes:
      - name: data
        hostPath:
          path: /raid/iiitaayushi
          type: Directory
      - name: nfs
        hostPath:
          path: /DATA1/iiitaayushi
          type: Directory
      - name: home
        hostPath:
          path: /home/iiitaayushi
          type: Directory
      - name: group
        hostPath:
          path: "/etc/group"
      - name: shadow
        hostPath:
          path: "/etc/shadow"
      - name: password
        hostPath:
          path: "/etc/passwd"
      restartPolicy: Never
  backoffLimit: 1
